name: Deploy to GitHub Pages

on:
  push:
    branches:
      - Bootstrap_Page
      - Responsive_Template

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./ # Adjust this if necessary
          publish_branch: gh-pages
